name: Positioner
favicon: null
layout_spectrum: 0.87784
typography_spectrum: 0.9689929236192256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#022940'
    - '#666d73'
    - '#c0b7b0'
    - '#6f031a'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.8471131462138146
purpose: []
