name: Positioner
favicon: null
layout_spectrum: 0.7851890213787556
typography_spectrum: 0.9689929236192256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.37003358849324286
  lightness: 0.7486086033750325
  saturation: 0.20137049513868988
  rhythmicContrast: 0.8471131462138146
purpose: []
